services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: woofer
      POSTGRES_USER: woofer
      POSTGRES_PASSWORD: woofer
    ports:
      - "5432:5432"
    volumes:
      - woofer_pgdata:/var/lib/postgresql/data

volumes:
  woofer_pgdata:
